MusicTickets/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MusicTickets.Controllers
{
    public class AboutController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MusicTickets/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicTickets.Models;
using MusicTickets.Data;
using System.Diagnostics;
using Accord.MachineLearning.Rules;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using System.Security.Claims;

namespace MusicTickets.Controllers
{
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            var musicTicketsContext = _context.Event.Include(@innerEvent => @innerEvent.EventGenre).Include(@innerEvent => @innerEvent.Stadium);

            ViewData["EventGenres"] = new SelectList(_context.Set<Genre>(), "Id", "Name");
            ViewData["Stadiums"] = new SelectList(_context.Set<Stadium>(), "Id", "Name");

            return View(await musicTicketsContext.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(string id)
        {
            ViewData["EventGenres"] = new SelectList(_context.Set<Genre>(), "Id", "Name");
            ViewData["Stadiums"] = new SelectList(_context.Set<Stadium>(), "Id", "Name");
            
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .Include(@innerEvent => @innerEvent.EventGenre)
                .Include(@innerEvent => @innerEvent.Stadium)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {
            ViewData["EventGenres"] = new SelectList(_context.Set<Genre>(), "Id", "Name");
            ViewData["Stadiums"] = new SelectList(_context.Set<Stadium>(), "Id", "Name");

            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Create([Bind("Id,EventDate,ArtistName,TotalTicketsNumber,AvailableTicketsNumber")] Event @event)
        {
            if (ModelState.IsValid)
            {
                @event.Stadium = _context.Stadium.Where(stadium => stadium.Id.Equals(Request.Form["Stadium"].ToString())).First();
                @event.EventGenre = _context.Genre.Where(genere => genere.Id.Equals(Request.Form["EventGenre"].ToString())).First();

                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["EventGenres"] = new SelectList(_context.Set<Genre>(), "Id", "Name");
            ViewData["Stadiums"] = new SelectList(_context.Set<Stadium>(), "Id", "Name");

            return View(@event);
        }

        [HttpGet]
        //public List<Event> Filter(string StadiumId, string GenreId, DateTime FromDT, DateTime ToDT, string ArtistName)
        public List<Event> Filter(string StadiumId, string GenreId, DateTime FromDT, DateTime ToDT, string ArtistName)
        {
            var musicTicketsContext = _context.Event.Include(@innerEvent => @innerEvent.EventGenre).
                                                     Include(@innerEvent => @innerEvent.Stadium);

            return musicTicketsContext.Where(e => (e.Stadium.Id == StadiumId || StadiumId == null) &&
                                      (e.EventGenre.Id == GenreId || GenreId == null) &&
                                      (e.EventDate >= FromDT || FromDT == DateTime.MinValue) &&
                                      (e.EventDate <= ToDT || ToDT == DateTime.MinValue) &&
                                      (e.ArtistName.Contains(ArtistName) || ArtistName == null)).ToList();
        }

        [HttpGet]
        public Boolean IsAdmin()
        {
            var userIdentity = (ClaimsIdentity)User.Identity;
            var claims = userIdentity.Claims;
            var roleClaimType = userIdentity.RoleClaimType;
            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();

            return roles.Any(currRole => currRole.Value.Equals("ADMIN"));
        }

        // GET: Events/Order/5
        public async Task<IActionResult> Order(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .SingleOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            ViewData["Event"] = @event;

            ViewData["RecomendedTicket"] = await this.GetTicketsForMI(id);

            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Order([Bind("Amount")] int Amount, string id)
        {
            if (ModelState.IsValid)
            {
                var eventSelected = _context.Event.SingleOrDefault(x => x.Id == id);
                if (eventSelected != null)
                {
                    var ticket = new Ticket() { Amount = Amount, Event = eventSelected };
                    _context.Ticket.Add(ticket);
                    eventSelected.AvailableTicketsNumber -= ticket.Amount;
                    var currUser = _context.ApplicationUser.SingleOrDefault(
                            x => x.Email.Equals(this.User.Identity.Name));
                    if (currUser.Tickets == null)
                    {
                        currUser.Tickets = new List<Ticket>();
                    }
                    currUser.Tickets.Add(ticket);
                    _context.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: Events/Edit/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.SingleOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            ViewData["EventGenres"] = new SelectList(_context.Set<Genre>(), "Id", "Name");
            ViewData["Stadiums"] = new SelectList(_context.Set<Stadium>(), "Id", "Name");

            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(string id, [Bind("Id,EventDate,ArtistName,TotalTicketsNumber,AvailableTicketsNumber")] Event @event)
        {
            if (id != @event.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    @event.Stadium = _context.Stadium.Where(stadium => stadium.Id.Equals(Request.Form["Stadium"].ToString())).First();
                    @event.EventGenre = _context.Genre.Where(genere => genere.Id.Equals(Request.Form["EventGenre"].ToString())).First();

                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["EventGenres"] = new SelectList(_context.Set<Genre>(), "Id", "Name");
            ViewData["Stadiums"] = new SelectList(_context.Set<Stadium>(), "Id", "Name");

            return View(@event);
        }

        // GET: Events/Delete/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // TODO: get the text
            var @event = await _context.Event
                .Include(@innerEvent => @innerEvent.EventGenre)
                .Include(@innerEvent => @innerEvent.Stadium)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var @event = await _context.Event.SingleOrDefaultAsync(m => m.Id == id);
            _context.Event.Remove(@event);
            try
            {
                await _context.SaveChangesAsync();

MusicTickets/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicTickets.Data;
using MusicTickets.Models;

namespace MusicTickets.Controllers
{
    public class GenresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GenresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
            return View(await _context.Genre.ToListAsync());
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .SingleOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.SingleOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .SingleOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var genre = await _context.Genre.SingleOrDefaultAsync(m => m.Id == id);
            _context.Genre.Remove(genre);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (Exception e)
            {
                throw new ApplicationException("You cant delete this genre!");
            }
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(string id)
        {
            return _context.Genre.Any(e => e.Id == id);
        }
    }
}

MusicTickets/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using MusicTickets.Models

@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["User"] = UserManager.GetUserName(User);
    ApplicationUser aplicationUser = await UserManager.GetUserAsync(User);
    IList<string> roles = null;

    if (aplicationUser != null)
    {
        roles = await UserManager.GetRolesAsync(aplicationUser);
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicTickets</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MusicTickets</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Events" asp-action="Index">Events</a></li>
                        <li><a asp-area="" asp-controller="Stadium" asp-action="Index">Stadium</a></li>
                        <li><a asp-area="" asp-controller="Tickets" asp-action="Index">Tickets</a></li>
                        <li><a asp-area="" asp-controller="Genres" asp-action="Index">Genres</a></li>
                        @if (roles != null && roles.Any(currRole => currRole.Equals("ADMIN")))
                        {
                            <li><a asp-area="" asp-controller="Statistics" asp-action="Index">Statistics</a></li>
                        }
                        <li><a asp-area="" asp-controller="About" asp-action="Index">About</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <aside>
        @await Html.PartialAsync("_LoginPartial")
    </aside>

    <div class="container body-content">
        <section>
            @RenderBody()
        </section>
        <hr />
        <footer>
            <p>&copy; 2018 - MusicTickets</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>